# Generated by Django 4.1.6 on 2023-02-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='cuisine.cuisine'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
