# Generated by Django 4.1.6 on 2023-02-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_restaurant_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
    ]
