# Generated by Django 4.1.6 on 2023-02-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_alter_cuisine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
