# Generated by Django 4.1.6 on 2023-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0005_alter_cuisine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
        ),
    ]
